name: Lock Issues

on: workflow_dispatch

jobs:
  lock:
    name: Lock Issues
    runs-on: ubuntu-latest
    steps:
      - name: Lock Issues
        uses: dessant/lock-threads@v3
        with:
          github-token: ${{ github.token }}
          issue-lock-reason: ''
          process-only: issues
